version: '3'
services:
  db:
    image: postgres:14.2
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  
volumes:
  db:
    driver: local